version 1

diff --git a/bin/project-add b/bin/project-add
--- a/bin/project-add
+++ b/bin/project-add
@@ -11,7 +11,30 @@ if [ $EUID -ne 0 ]; then
   exit 1
 fi
 
-PROJECT_NAME="$1"
+# Show usage
+usage() {
+  cat <<- _EOF_
+Create a new project
+Example run shell: project-add -n=name -g=remote_repos_adress
+
+  -n, --name     Name project. !Required!
+  -g, --git      Auto clone from remote repository.
+	-h, --help     Help - show this menu.
+_EOF_
+  exit 1
+}
+
+PROJECT_NAME=
+REMOTE_REP_ADRESS=
+
+for i in "$@"; do
+  case ${i} in
+    -n=*|--name=*) PROJECT_NAME="${i#*=}" ;;
+    -g=*|--git=*) REMOTE_REP_ADRESS="${i#*=}" ;;
+    *) usage; exit 1 ;;
+  esac
+done
+
 PROJECT_PATH="/home/${PROJECT_USER}"
 PROJECT_PATH_FULL=$(echo "${PROJECT_PATH}/${PROJECT_NAME}/httpdocs")
 
@@ -27,8 +50,16 @@ if [ -d ${PROJECT_PATH_FULL} ]; then
   exit 1
 fi
 
-mkdir -p ${PROJECT_PATH_FULL} \
-  && wget -qO /dev/null ${URL_BITRIXSETUP} -P ${PROJECT_PATH_FULL} \
-  && wget -qO /dev/null ${URL_BITRIXRESTOR} -P ${PROJECT_PATH_FULL} \
-  && chown -R "${PROJECT_USER}:${PROJECT_GROUP}" ${PROJECT_PATH_FULL} \
-  && chmod -R g+rwx ${PROJECT_PATH_FULL}
+mkdir -p ${PROJECT_PATH_FULL} || (echo "Can not create project folder"; exit 1;)
+ 
+if [ -n "${REMOTE_REP_ADRESS}" ]; then 
+	sudo git clone "${REMOTE_REP_ADRESS}" ${PROJECT_PATH_FULL} || echo "Error while clonnig repository" 
+fi
+
+sudo wget  -P ${PROJECT_PATH_FULL} -q ${URL_BITRIXSETUP} \
+  && sudo wget  -P ${PROJECT_PATH_FULL} -q ${URL_BITRIXRESTOR} \
+  && sudo chown -R "${PROJECT_USER}:${PROJECT_GROUP}" ${PROJECT_PATH_FULL} \
+  && sudo chmod -R g+rwx ${PROJECT_PATH_FULL}
+
+#maybe create remote repository(seperate script)
+#при внесении изменений в в уд. репозиторий автоматически pull 
diff --git a/bin/sandbox-add b/bin/sandbox-add
--- a/bin/sandbox-add
+++ b/bin/sandbox-add
@@ -11,8 +11,33 @@ if [ $EUID -ne 0 ]; then
   exit 1
 fi
 
-PROJECT_NAME="$1"
-SANDBOX_USER="$2"
+# Show usage
+usage() {
+  cat <<- _EOF_
+Create a new sandbox
+Example run shell: project-add -p=project_name -u=user -g=remote_repos_adress
+
+  -p, --project  Name project. !Required!
+  -u, --user     User. !Required!
+	-g, --git      Auto clone from remote repository.
+	-h, --help     Help - show this menu.
+_EOF_
+  exit 1
+}
+
+PROJECT_NAME=
+SANDBOX_USER=
+REMOTE_REP_ADRESS=
+
+for i in "$@"; do
+  case ${i} in
+    -p=*|--project=*) PROJECT_NAME="${i#*=}" ;;
+		-u=*|--user=*) SANDBOX_USER="${i#*=}" ;;
+    -g=*|--git=*) REMOTE_REP_ADRESS="${i#*=}" ;; #default - project repository adress
+    *) usage; exit 1 ;;
+  esac
+done
+
 SANDBOX_PATH=$(echo "/home/${SANDBOX_USER}/www/${PROJECT_NAME}")
 
 if [ "${PROJECT_NAME}" == '' ] || [ "${SANDBOX_USER}" == '' ]; then
@@ -30,11 +55,23 @@ if [ -d "${SANDBOX_PATH}" ]; then
   exit 1
 fi
 
-mkdir -p "${SANDBOX_PATH}/${PROJECT_NAME}"
-mkdir -p "${SANDBOX_PATH}/${PROJECT_NAME}/httpdocs"
+mkdir -p "${SANDBOX_PATH}"
+mkdir -p "${SANDBOX_PATH}/httpdocs"
 
-ln -s "/home/${PROJECT_USER}/${PROJECT_NAME}/httpdocs/bitrix" "${SANDBOX_PATH}/${PROJECT_NAME}/httpdocs"
-ln -s "/home/${PROJECT_USER}/${PROJECT_NAME}/httpdocs/upload" "${SANDBOX_PATH}/${PROJECT_NAME}/httpdocs"
+if [ -z "${REMOTE_REP_ADRESS}"] then
+	CURRENT_DIR=pwd
+	cd "/home/${PROJECT_USER}/${PROJECT_NAME}/httpdocs"
+	STR=git remote -v ?"^origin"?
+	REMOTE_REP_ADRESS=`expr match "${STR}" '\<(https|ssh|git):\/\/[^ ]+\>'`
+	cd "${CURRENT_DIR}"
+fi
 
-chown -R "${SANDBOX_USER}:${PROJECT_GROUP}" "${SANDBOX_PATH}/${PROJECT_NAME}/httpdocs"
-chmod -R g+rwx "${SANDBOX_PATH}/${PROJECT_NAME}/httpdocs"
+
+if [ -n "${REMOTE_REP_ADRESS" ]; then git clone ${REMOTE_REP_ADRESS} "${SANDBOX_PATH}/httpdocs" fi \
+|| echo "Error while clonning repository";
+
+ln -s "/home/${PROJECT_USER}/${PROJECT_NAME}/httpdocs/bitrix" "${SANDBOX_PATH}/httpdocs/bitrix"
+ln -s "/home/${PROJECT_USER}/${PROJECT_NAME}/httpdocs/upload" "${SANDBOX_PATH}/httpdocs/upload"
+
+chown -R "${SANDBOX_USER}:${PROJECT_GROUP}" "${SANDBOX_PATH}/httpdocs"
+chmod -R g+rwx "${SANDBOX_PATH}/httpdocs"
diff --git a/bin/user-add b/bin/user-add
--- a/bin/user-add
+++ b/bin/user-add
@@ -4,6 +4,8 @@
 # For the full copyright and license information, please view the LICENSE
 # file that was distributed with this source code.
 
+source "/etc/git-sandbox.conf"
+
 if [ $EUID -ne 0 ]; then
   echo "This script should be run as root." > /dev/stderr
   exit 1
@@ -28,5 +30,15 @@ if [ $? == 0 ]; then
   echo "User '$USER_NAME' has been added."
 else
   echo "Failed to add a user."
+	exit 1
 fi
+
+usermod -g ${PROJECT_GROUP} ${USER_NAME}
+if [ $? == 0 ]; then
+  echo "User '$USER_NAME' has been added to ${PROJECT_GROUP} group."
+else
+  echo "Failed to add a user to ${PROJECT_GROUP} group."
+	exit 1
+fi
+
 
