Fix bugs

diff --git a/bin/project-add b/bin/project-add
--- a/bin/project-add
+++ b/bin/project-add
@@ -31,12 +31,9 @@ for i in "$@"; do
   case ${i} in
     -n=*|--name=*) PROJECT_NAME="${i#*=}" ;;
     -g=*|--git=*) REMOTE_REP_ADRESS="${i#*=}" ;;
-    *) usage; exit 1 ;;
+  *) usage; exit 1 ;;
   esac
 done
-
-PROJECT_PATH="/home/${PROJECT_USER}"
-PROJECT_PATH_FULL=$(echo "${PROJECT_PATH}/${PROJECT_NAME}/httpdocs")
 
 URL_BITRIXSETUP="http://www.1c-bitrix.ru/download/scripts/bitrixsetup.php"
 URL_BITRIXRESTOR="http://www.1c-bitrix.ru/download/scripts/restore.php"
@@ -45,21 +42,21 @@ if [ "${PROJECT_NAME}" == '' ]; then
   read -p "Enter name project and press [ENTER]: " PROJECT_NAME
 fi
 
-if [ -d ${PROJECT_PATH_FULL} ]; then
+PROJECT_PATH="/home/${PROJECT_USER}"
+PROJECT_PATH_FULL="${PROJECT_PATH}/${PROJECT_NAME}/httpdocs"
+
+if [ -d "${PROJECT_PATH_FULL}" ]; then
   echo "Project '${PROJECT_NAME}' already exists."
   exit 1
 fi
 
-mkdir -p ${PROJECT_PATH_FULL} || (echo "Can not create project folder"; exit 1;)
+mkdir -p "${PROJECT_PATH_FULL}" || (echo "Can not create project folder"; exit 1;)
  
 if [ -n "${REMOTE_REP_ADRESS}" ]; then 
-	sudo git clone "${REMOTE_REP_ADRESS}" ${PROJECT_PATH_FULL} || echo "Error while clonnig repository" 
+  git clone "${REMOTE_REP_ADRESS}" "${PROJECT_PATH_FULL}" || echo "Error while clonnig repository" 
 fi
 
-sudo wget  -P ${PROJECT_PATH_FULL} -q ${URL_BITRIXSETUP} \
-  && sudo wget  -P ${PROJECT_PATH_FULL} -q ${URL_BITRIXRESTOR} \
-  && sudo chown -R "${PROJECT_USER}:${PROJECT_GROUP}" ${PROJECT_PATH_FULL} \
-  && sudo chmod -R g+rwx ${PROJECT_PATH_FULL}
-
-#maybe create remote repository(seperate script)
-#при внесении изменений в в уд. репозиторий автоматически pull 
+wget  -P ${PROJECT_PATH_FULL} -q ${URL_BITRIXSETUP} \
+  && wget  -P ${PROJECT_PATH_FULL} -q ${URL_BITRIXRESTOR} \
+  && chown -R "${PROJECT_USER}:${PROJECT_GROUP}" ${PROJECT_PATH_FULL} \
+  && chmod -R g+rwx ${PROJECT_PATH_FULL}
