Rename bins

diff --git a/bin/user-add b/bin/user-add
--- a/bin/user-add
+++ b/bin/user-add
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/bin/sh
 
 # This file is part of the Studio Fact package.
 # For the full copyright and license information, please view the LICENSE
@@ -10,20 +10,23 @@ if [ $EUID -ne 0 ]; then
 fi
 
 USER_NAME=$1
+USER_PASSWORD=$2
 
-if [ "$USER_NAME" == '' ]; then
+if [ "$USER_NAME" == '' ] || [ "$USER_PASSWORD" == '' ]; then
   read -p "Enter name and press [ENTER]: " USER_NAME
+  read -s -p "Enter password and press [ENTER]: " USER_PASSWORD
 fi
 
 egrep "^$USER_NAME" /etc/passwd >/dev/null
-if [ $? != 0 ]; then
-  echo -e "$USER_NAME not exists. Please enter a different username."
+if [ $? -eq 0 ]; then
+  echo -e "$USER_NAME already exists. Please enter a different username."
   exit 1
 fi
 
-deluser --remove-home ${USER_NAME}
+useradd -m -p ${USER_PASSWORD} ${USER_NAME}
 if [ $? == 0 ]; then
-  echo "User '$USER_NAME' has been deleted."
+  echo "User '$USER_NAME' has been added."
 else
-  echo "Failed to delete a user."
+  echo "Failed to add a user."
 fi
+
